apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-petclinic
  template:
    metadata:
      labels:
        app: azure-petclinic
    spec:      
      containers:
      - name: azure-petclinic
        image: acrpetclinic1.azurecr.io/petclinic
        ports:
        - containerPort: 8080
          name: petclinic
